# version: '3.8'

# services:
#   app:
#     build: .
#     container_name: php-app
#     ports:
#       - "8000:80"
#     volumes:
#       - .:/var/www/html
#     depends_on:
#       - db

#   db:
#     image: mysql:8.0
#     container_name: mysql-db
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root_password
#       MYSQL_DATABASE: database_name
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#     ports:
#       - "3306:3306"
#     volumes:
#       - db_data:/var/lib/mysql

# volumes:
#   db_data:
